# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HazelcastCommandlineClient < Formula
  desc "Hazelcast Command-line Client Project"
  homepage "https://github.com/hazelcast/hazelcast-commandline-client"
  version "5.2.0-beta2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hazelcast/hazelcast-commandline-client/releases/download/v5.2.0-beta2/hazelcast-commandline-client_5.2.0-beta2_Darwin_arm64.tar.gz"
      sha256 "0df44f5a987aeed5a71cb726d5992f2e3c98c6c6940b04f46ef385ed81632935"

      def install
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hazelcast/hazelcast-commandline-client/releases/download/v5.2.0-beta2/hazelcast-commandline-client_5.2.0-beta2_Darwin_x86_64.tar.gz"
      sha256 "d5018d492ac34f97e734d4ae92af9f2ee2751744eede2dda678d6e1e5b6d2b9c"

      def install
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hazelcast/hazelcast-commandline-client/releases/download/v5.2.0-beta2/hazelcast-commandline-client_5.2.0-beta2_Linux_arm64.tar.gz"
      sha256 "ad52f2c67df4f88ea83e0e51623268720c969c4797233dd6bddd266b0858ee0a"

      def install
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hazelcast/hazelcast-commandline-client/releases/download/v5.2.0-beta2/hazelcast-commandline-client_5.2.0-beta2_Linux_x86_64.tar.gz"
      sha256 "7745cb0222b2270ba7301ff4f816d2ef00afbd09d90b3a18c63489df3a72f85c"

      def install
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
  end

  def post_install
    ohai "Example usages:
    * `hzc` - start an interactive shell 🚀
    * `hzc map --name my-map put --key hello --value world` - put entry into map"
        completion_warning = <<~EOS
          ⚠️  To have superior experience, enable autocompletion on Brew. ⚠️
          You need to enable autocompletion just once for Brew. If it is already enabled, you can skip this part.
          ▪ For Bash users:
            1) `brew install bash-completion` and follow the printed \"Caveats\" section. Example \"Caveats\" instructions:
               Add the following line to your ~/.bash_profile:
               # !! Note that paths may differ depending on your installation, so you should follow the Caveats section on your system.
               [[ -r \"/home/ubuntu/.linuxbrew/etc/profile.d/bash_completion.sh\" ]] && . \"/home/ubuntu/.linuxbrew/etc/profile.d/bash_completion.sh\"
            2) `source ~/.bash_profile`
          ▪ For Zsh users:
          Follow https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
        EOS
        print completion_warning
  end
end
