# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HazelcastCommandlineClient < Formula
  desc "Hazelcast Command line Client"
  homepage "https://github.com/hazelcast/hazelcast-commandline-client"
  version "5.2.0-beta2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/hazelcast/hazelcast-commandline-client/releases/download/v5.2.0-beta2/hazelcast-commandline-client_5.2.0-beta2_Darwin_arm64.tar.gz"
      sha256 "ff66bb89f120924f19fcd389dcd983bf0effb1243cd4cc786c91b3225bbc28b1"

      def install
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hazelcast/hazelcast-commandline-client/releases/download/v5.2.0-beta2/hazelcast-commandline-client_5.2.0-beta2_Darwin_x86_64.tar.gz"
      sha256 "af9342c8d0d5ed86926841f2e9c8183d34b0c4e7e9f4184d34eb1ca886db081d"

      def install
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hazelcast/hazelcast-commandline-client/releases/download/v5.2.0-beta2/hazelcast-commandline-client_5.2.0-beta2_Linux_arm64.tar.gz"
      sha256 "bf2b3b52be9a4645d6785cc3eebf3fc9adb0ea7d14a95226ee3f93d56ea8aa7b"

      def install
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/hazelcast/hazelcast-commandline-client/releases/download/v5.2.0-beta2/hazelcast-commandline-client_5.2.0-beta2_Linux_x86_64.tar.gz"
      sha256 "10ad361e9e2f12b9e6b35a3798d421fb4ce8b8b9879a8c6b80aebd7750af7ca7"

      def install
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
  end

  def post_install
    ohai "Example usages:
    * `hzc` - start an interactive shell 🚀
    * `hzc map --name my-map put --key hello --value world` - put entry into map"
        completion_warning = <<~EOS
          ⚠️  To have superior experience, enable autocompletion on Brew. ⚠️
          You need to enable autocompletion just once for Brew. If it is already enabled, you can skip this part.
          ▪ For Bash users:
            1) `brew install bash-completion` and follow the printed \"Caveats\" section. Example \"Caveats\" instructions:
               Add the following line to your ~/.bash_profile:
               # !! Note that paths may differ depending on your installation, so you should follow the Caveats section on your system.
               [[ -r \"/home/ubuntu/.linuxbrew/etc/profile.d/bash_completion.sh\" ]] && . \"/home/ubuntu/.linuxbrew/etc/profile.d/bash_completion.sh\"
            2) `source ~/.bash_profile`
          ▪ For Zsh users:
          Follow https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
        EOS
        print completion_warning
  end
end
